'use client'

import { useState } from 'react'
import { useRouter } from 'next/navigation'
import { Modal } from './Modal'

export interface AiTemplateModalProps {
  isOpen: boolean
  onClose: () => void
}

const TEMPLATE_TYPES = ['NDA', 'Sales Contract', 'Service Agreement', 'Employment Agreement', 'Custom']
const INDUSTRIES = ['Legal', 'Sales', 'HR', 'Real Estate', 'Healthcare', 'Technology', 'Finance', 'Other']

interface GeneratedTemplate {
  title: string
  content: string
  fields: { type: string; label: string; x: number; y: number }[]
}

export function AiTemplateModal({ isOpen, onClose }: AiTemplateModalProps) {
  const [templateType, setTemplateType] = useState(TEMPLATE_TYPES[0])
  const [industry, setIndustry] = useState(INDUSTRIES[0])
  const [keyTerms, setKeyTerms] = useState('')
  const [loading, setLoading] = useState(false)
  const [generated, setGenerated] = useState<GeneratedTemplate | null>(null)
  const [status, setStatus] = useState('')

  const router = useRouter()

  const generateTemplate = async () => {
    if (!keyTerms.trim()) {
      setStatus('Please describe your template requirements.')
      return
    }
    setLoading(true)
    setStatus('Generating template...')
    setGenerated(null)

    // Simulate AI generation (replace with real API call when ANTHROPIC_API_KEY is set)
    await new Promise((r) => setTimeout(r, 1500))

    const mockTemplate: GeneratedTemplate = {
      title: `${templateType} - ${industry}`,
      content: `${templateType} Agreement\n\nThis ${templateType.toLowerCase()} ("Agreement") is entered into as of the date last signed below.\n\nParties:\n${keyTerms}\n\nIndustry: ${industry}\n\nThis template was generated by SignProz AI. Review and customize before use.`,
      fields: [
        { type: 'signature', label: 'Party A Signature', x: 35, y: 70 },
        { type: 'signature', label: 'Party B Signature', x: 65, y: 70 },
        { type: 'date', label: 'Effective Date', x: 50, y: 80 },
      ],
    }

    setGenerated(mockTemplate)
    setStatus('Template generated successfully. Review and use it below.')
    setLoading(false)
  }

  const useTemplate = () => {
    if (!generated) return
    // Navigate to dashboard with template data encoded
    const params = new URLSearchParams({
      template: generated.title,
      type: templateType,
      industry,
    })
    router.push(`/templates?${params.toString()}`)
    onClose()
  }

  const handleClose = () => {
    setKeyTerms('')
    setGenerated(null)
    setStatus('')
    onClose()
  }

  return (
    <Modal isOpen={isOpen} onClose={handleClose} title="AI Template Generator" maxWidth="max-w-2xl">
      <div className="space-y-4">
        {/* Step 1: Template type */}
        <div>
          <label className="block text-sm font-semibold text-slate-800 mb-2">Step 1: Template type</label>
          <select
            value={templateType}
            onChange={(e) => setTemplateType(e.target.value)}
            className="w-full border border-slate-200 rounded-xl p-3 text-sm focus:ring-2 focus:ring-cyan-200 focus:border-cyan-400 outline-none"
          >
            {TEMPLATE_TYPES.map((t) => (
              <option key={t} value={t}>{t}</option>
            ))}
          </select>
        </div>

        {/* Step 2: Industry */}
        <div>
          <label className="block text-sm font-semibold text-slate-800 mb-2">Step 2: Industry</label>
          <select
            value={industry}
            onChange={(e) => setIndustry(e.target.value)}
            className="w-full border border-slate-200 rounded-xl p-3 text-sm focus:ring-2 focus:ring-cyan-200 focus:border-cyan-400 outline-none"
          >
            {INDUSTRIES.map((i) => (
              <option key={i} value={i}>{i}</option>
            ))}
          </select>
        </div>

        {/* Step 3: Key terms */}
        <div>
          <label className="block text-sm font-semibold text-slate-800 mb-2">Step 3: Key terms & parties</label>
          <textarea
            value={keyTerms}
            onChange={(e) => setKeyTerms(e.target.value)}
            placeholder="Example: 2-party SaaS agreement with NDA clause, payment terms, and signature blocks. Parties: Acme Corp and Beta LLC."
            className="w-full border border-slate-200 rounded-xl p-3 text-sm min-h-[100px] focus:ring-2 focus:ring-cyan-200 focus:border-cyan-400 outline-none resize-none"
          />
        </div>

        <div className="flex items-center gap-3 flex-wrap">
          <button
            onClick={generateTemplate}
            disabled={loading}
            className="bg-blue-600 text-white px-5 py-2.5 rounded-xl text-sm font-semibold hover:bg-blue-700 disabled:opacity-40 disabled:cursor-not-allowed"
          >
            {loading ? 'Generating...' : 'Generate Template'}
          </button>
          {generated && (
            <button
              onClick={useTemplate}
              className="bg-emerald-600 text-white px-5 py-2.5 rounded-xl text-sm font-semibold hover:bg-emerald-700"
            >
              Use Template
            </button>
          )}
          {status && <span className="text-xs text-slate-500">{status}</span>}
        </div>

        {/* Generated preview */}
        <div className="rounded-xl border border-slate-100 bg-slate-50/80 p-4 min-h-[120px]">
          {generated ? (
            <div className="space-y-3">
              <div>
                <h4 className="font-bold text-slate-900 text-sm">{generated.title}</h4>
                <p className="text-xs text-slate-500 mt-0.5">AI-generated template</p>
              </div>
              <pre className="text-sm text-slate-600 whitespace-pre-wrap font-sans">{generated.content}</pre>
              {generated.fields.length > 0 && (
                <div>
                  <p className="text-xs font-semibold text-slate-500 mb-1">Included fields:</p>
                  <div className="flex flex-wrap gap-1.5">
                    {generated.fields.map((f, i) => (
                      <span key={i} className="field-chip text-xs">
                        {f.type === 'signature' ? '✍️' : '📅'} {f.label}
                      </span>
                    ))}
                  </div>
                </div>
              )}
            </div>
          ) : (
            <p className="text-sm text-slate-400 text-center py-4">
              Draft summary appears here. Click <strong>Generate Template</strong> to create a starter template.
            </p>
          )}
        </div>
      </div>
    </Modal>
  )
}
